name: runner-space-test

on:
  workflow_dispatch:

jobs:
  mimic:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69
      volumes:
        # The updater makes heavy use of /tmp files.
        - /tmp:/tmp
        - /usr:/mnt/usr
        - /opt:/mnt/opt
    steps:
    - name: Free up disk space
      shell: bash
      run: |
        set +e
        set -x

        df -h

        docker system prune --force --all
        for delete in /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL; do
          rm -rf "/mnt${delete:?}"
        done
        
        df -h
