name: runner-space-test

on:
  workflow_dispatch:

jobs:
  download-nvd:
    runs-on: ubuntu-latest
    env:
      EONE: ""
      ETWO: "NOTEMPTY"
    steps:
    - name: step1
      shell: bash
      run: |
        set -eu
        since_time=$(date -u -d '24 hours ago' '+%a, %d %b %Y %H:%M:%S GMT')

        code=$(curl \
            -o nvd.zip \
            -w "%{http_code}" \
            -H "If-Modified-Since: $since_time" \
            "$url")

        ls -lha | grep -i nvd || true
        echo "code: $code"
        echo "$code" | grep -q 200

    - id: upload-artifact-try1
      uses: actions/upload-artifact@v4
      with:
        name: nvd
        path: nvd.zip
        if-no-files-found: error
      continue-on-error: true

  upload-release-vulnerabilities:
    runs-on: ubuntu-latest
    needs:
    - download-nvd
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: nvd
        path: .
      continue-on-error: true
    - name: doit
      shell: bash
      run: |
        echo "PWD: $(pwd)"

        ls -lah . | grep -i nvd
