name: Blank

on:
  workflow_dispatch:

jobs:
  doit:
    runs-on: ubuntu-latest
    env:
      ROX_PRODUCT_VERSION: 1.2.3
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69
      volumes:
        # The updater makes heavy use of /tmp files.
        - /tmp:/tmp
    steps:
    - name: doit
      shell: bash
      run: |
        cmd=()
        if [[ "${{ github.ref_name }}" != "main" ]]; then
          echo "Ref '${{ github.ref_name }}' is not master."
          cmd+=(echo "Would do: ")
        fi
        "${cmd[@]}" curl "https://example.com"

        echo "$(date)" > file.txt
    - name: Create artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.ref_name != 'main' }}
      with:
        name: ${{ env.ROX_PRODUCT_VERSION }}
        path: file.txt
