name: blank

on:
  workflow_dispatch:
    inputs:
      exit-with-error:
        type: boolean
        description: Force an error

jobs:
  doit:
    runs-on: ubuntu-latest
    env:
      ROX_PRODUCT_VERSION: 1.2.3
    steps:
    - name: doit
      shell: bash
      run: |
        echo "Ref Name: ${{ github.ref_name }}"

        bucket="gs://definitions.stackrox.io/v4/vulnerability-bundles"
        if [[ "${{ github.ref_name }}" != "master" ]]; then
          # If dispatched from a branch other then master, upload bundles
          # to the test bucket instead
          bucket="gs://scanner-v4-test/vulnerability-bundles"
        fi

        echo "Copying ${{ env.ROX_PRODUCT_VERSION }} to $bucket"
        echo gsutil cp -r "${{ env.ROX_PRODUCT_VERSION }}" "$bucket"

        ## force failure
        if [[ "${{ github.event.inputs.exit-with-error }}" == "true" ]]; then
          exit 1
        fi
  
  send-fake-notification:
    runs-on: ubuntu-latest
    needs:
    - doit
    if: ${{ failure() && github.ref_name == 'main' }}
    steps:
    - name: Send Slack notification on workflow failure
      run: |
        curl -sSi https://example.com/fail
