name: runner-space-test

on:
  workflow_dispatch:

jobs:
  doit:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69
      volumes:
        # The updater makes heavy use of /tmp files.
        - /tmp:/tmp
    steps:
    - name: doit
      env:
        ROX_PRODUCT_VERSION: 1.2.3
      shell: bash
      run: |
        if [[ "${{ github.ref_name }}" == "master" ]]; then
          cmd+=(echo "Would do")
        fi
        "${cmd[@]}" curl https://example.com gs://definitions.stackrox.io/v4/vulnerability-bundles"
