name: runner-space-test

on:
  workflow_dispatch:

jobs:
  download-nvd:
    runs-on: ubuntu-latest
    env:
      EONE: ""
      ETWO: "NOTEMPTY"
    steps:
    - name: step1
      shell: bash
      run: |
        curl \
            -o nvd.zip \
            -w "%{http_code}" \
            "https://definitions.stackrox.io/v4/nvd/nvd-api.zip"

        ls -lha | grep -i nvd
    - id: upload-artifact-try1
      uses: actions/upload-artifact@v4
      with:
        name: nvd
        path: nvd.zip
        if-no-files-found: error
      continue-on-error: true

  upload-release-vulnerabilities:
    runs-on: ubuntu-latest
    needs:
    - download-nvd
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: nvd
        path: .
      continue-on-error: true
    - name: doit
      shell: bash
      run: |
        ls -lah . | grep -i nvd
