name: blank

on:
  workflow_dispatch:
    inputs:
      exit-with-error:
        type: boolean
        description: Force an error

jobs:
  doit:
    runs-on: ubuntu-latest
    env:
      ROX_PRODUCT_VERSION: 1.2.3
    steps:
    - name: doit
      shell: bash
      run: |
        cmd=()
        if [[ "${{ github.ref_name }}" != "main" ]]; then
          echo "Ref '${{ github.ref_name }}' is not master."
          cmd+=(echo "Would do: ")
        fi
        "${cmd[@]}" curl -sSi "https://example.com"

        echo "$(date)" > file.txt

        ## force failure
        if [[ "${{ github.event.inputs.exit-with-error }}" == "true" ]]; then
          exit 1
        fi

    - name: Create artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.ref_name != 'main' }}
      with:
        name: ${{ env.ROX_PRODUCT_VERSION }}
        path: file.txt
  
  send-fake-notification:
    runs-on: ubuntu-latest
    if: failure() && ${{ github.ref_name == 'master' }}
    steps:
    - name: Send Slack notification on workflow failure
      run: |
        curl -sSi https://example.com/fail
