name: runner-space-test

on:
  workflow_dispatch:

jobs:
  mimic:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.69
      volumes:
        # The updater makes heavy use of /tmp files.
        - /tmp:/tmp
        - /usr:/mnt/usr
        - /opt:/mnt/opt
    steps:
    - name: Free up disk space
      shell: bash
      run: |
        set +e
        set -x

        df -h

        docker system prune --force --all
        for delete in /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL; do
          rm -rf "/mnt${delete:?}"
        done
        
        df -h
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Space Before
        run: |
          df --si
          du -sh /usr/local/lib/android || true
          du -sh /usr/share/dotnet || true
          du -sh /opt/ghc || true
          du -sh /usr/local/.ghcup || true
          du -sh "$AGENT_TOOLSDIRECTORY" || true

          ls -la "$AGENT_TOOLSDIRECTORY" || true
          
      - name: Do clean
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo apt-get remove -y '^aspnetcore-.*' || echo "::warning::The command [sudo apt-get remove -y '^aspnetcore-.*'] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^dotnet-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^dotnet-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^llvm-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^llvm-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y 'php.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y 'php.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^mongodb-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mongodb-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing || echo "::warning::The command [sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing] failed to complete successfully. Proceeding..."
          sudo apt-get autoremove -y || echo "::warning::The command [sudo apt-get autoremove -y] failed to complete successfully. Proceeding..."
          sudo apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
          sudo docker image prune --all --force || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo swapoff -a || true
          sudo rm -f /mnt/swapfile || true
          free -h
          
      - name: Check Space After
        run: |
          df --si
          du -sh /usr/local/lib/android || true
          du -sh /usr/share/dotnet || true
          du -sh /opt/ghc || true
          du -sh /usr/local/.ghcup || true
          du -sh "$AGENT_TOOLSDIRECTORY" || true
