name: runner-space-test

on:
  workflow_dispatch:

jobs:
  mimic:
    runs-on: ubuntu-latest
    env:
      EONE: ""
      ETWO: "NOTEMPTY"
    steps:
    - name: step1
      shell: bash
      run: |
        echo "EONE: $EONE"
        echo "ETWO: $ETWO"
